/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnterpriseAdmin;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import UserInterface.Analysis.LeadCompoundAnalysisJPanel;
import UserInterface.Analysis.PassOrFailJPanel;
import UserInterface.Analysis.PopularDrugJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author joseph antony
 */
public class EnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {

    public JPanel userProcessContainer;
    public Enterprise enterprise;
    public Network network;
    public Ecosystem system;
    public UserAccount userAccount;

    /**
     * Creates new form EnterpriseAdminWorkArea
     */
    public EnterpriseAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Network network, Ecosystem system, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        this.userAccount = account;
        if (!enterprise.getFunction().equalsIgnoreCase("Research & Development")) {
            btnStudy.hide();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageOrganization = new javax.swing.JButton();
        btnStudy = new javax.swing.JButton();
        btnViewWorkQueue = new javax.swing.JButton();
        btnAnalysis = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel1.setText("Enterprise Admin Work Area");

        btnManageOrganization.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnManageOrganization.setText("Create Organization");
        btnManageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationActionPerformed(evt);
            }
        });

        btnStudy.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnStudy.setText("View Study details");
        btnStudy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudyActionPerformed(evt);
            }
        });

        btnViewWorkQueue.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnViewWorkQueue.setText("View Work Queue");
        btnViewWorkQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewWorkQueueActionPerformed(evt);
            }
        });

        btnAnalysis.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAnalysis.setText("Analysis");
        btnAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStudy, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnManageOrganization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewWorkQueue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAnalysis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(757, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(149, 149, 149)
                .addComponent(btnManageOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnViewWorkQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnStudy, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationActionPerformed
        CreateOrganizationJPanel manageOrganizationJPanel = new CreateOrganizationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrganizationActionPerformed

    private void btnViewWorkQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewWorkQueueActionPerformed
        if (enterprise.getFunction().equalsIgnoreCase("Research & Development")) {
            RandDEnterpriseAdminWorkQueueJPanel RandDEnterpriseAdminWorkQueueJPanel = new RandDEnterpriseAdminWorkQueueJPanel(userProcessContainer, enterprise, network, userAccount);
            userProcessContainer.add("RandDEnterpriseAdminWorkQueueJPanel", RandDEnterpriseAdminWorkQueueJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else if (enterprise.getFunction().equalsIgnoreCase("Clinical Study")) {
            ClinicalEnterpriseAdminWorkQueueJPanel ClinicalEnterpriseAdminWorkQueueJPanel = new ClinicalEnterpriseAdminWorkQueueJPanel(userProcessContainer, enterprise, network, system, userAccount);
            userProcessContainer.add("ClinicalEnterpriseAdminWorkQueueJPanel", ClinicalEnterpriseAdminWorkQueueJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else if (enterprise.getFunction().equalsIgnoreCase("Production")){
            MedicineRequestEnterpriseAdminWorkQueueJPanel medicineRequestEnterpriseAdminWorkQueue = new MedicineRequestEnterpriseAdminWorkQueueJPanel(userProcessContainer, enterprise, system, userAccount);
            userProcessContainer.add("medicineRequestEnterpriseAdminWorkQueue", medicineRequestEnterpriseAdminWorkQueue);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewWorkQueueActionPerformed

    private void btnAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysisActionPerformed
        if (enterprise.getFunction().equalsIgnoreCase("Research & Development")) {
            LeadCompoundAnalysisJPanel panel = new LeadCompoundAnalysisJPanel(userProcessContainer, system, network);
            userProcessContainer.add("panel", panel);
        }
        else if (enterprise.getFunction().equalsIgnoreCase("Clinical Study")) {
            PassOrFailJPanel panel = new PassOrFailJPanel(userProcessContainer, system, network, enterprise);
            userProcessContainer.add("panel", panel);
        }
        else if (enterprise.getFunction().equalsIgnoreCase("Production")){
            PopularDrugJPanel panel = new PopularDrugJPanel(userProcessContainer, system, network, enterprise);
            userProcessContainer.add("panel", panel);
        }
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnAnalysisActionPerformed

    private void btnStudyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudyActionPerformed
        if (enterprise.getFunction().equalsIgnoreCase("Research & Development")) {
            EnterpriseAdminDrugHistoryJPanel panel = new EnterpriseAdminDrugHistoryJPanel(userProcessContainer, system.getDrugList());
            userProcessContainer.add("panel", panel);
        }
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnStudyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalysis;
    private javax.swing.JButton btnManageOrganization;
    private javax.swing.JButton btnStudy;
    private javax.swing.JButton btnViewWorkQueue;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
