/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ScientistRole;

import Business.Compound.Compound;
import Business.Ecosystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CompoundWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.WorkRequest.Status;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joseph antony
 */
public class CompScientistWorkAreaJPanel extends javax.swing.JPanel {

    public JPanel userProcessContainer;
    public UserAccount account;
    public Organization organization;
    public Ecosystem system;

    /**
     * Creates new form ScientistWorkArea
     */
    public CompScientistWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.account = account;
        this.system = system;
        populateCompoundHistory();
        populateWorkQueue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkQueue = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCompoundHistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCreateCompound = new javax.swing.JButton();
        btnRequest = new javax.swing.JButton();
        btnMessageToAdmin = new javax.swing.JButton();
        txtMessage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));

        tblWorkQueue.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblWorkQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compound", "Sender", "Receiver", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkQueue);
        if (tblWorkQueue.getColumnModel().getColumnCount() > 0) {
            tblWorkQueue.getColumnModel().getColumn(0).setResizable(false);
            tblWorkQueue.getColumnModel().getColumn(1).setResizable(false);
            tblWorkQueue.getColumnModel().getColumn(2).setResizable(false);
            tblWorkQueue.getColumnModel().getColumn(4).setResizable(false);
        }

        tblCompoundHistory.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblCompoundHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compound", "Molecular Formula", "Discovery Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCompoundHistory);
        if (tblCompoundHistory.getColumnModel().getColumnCount() > 0) {
            tblCompoundHistory.getColumnModel().getColumn(1).setResizable(false);
            tblCompoundHistory.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel1.setText("Scientist Work Area");

        btnCreateCompound.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCreateCompound.setText("Create Compound");
        btnCreateCompound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCompoundActionPerformed(evt);
            }
        });

        btnRequest.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRequest.setText("Request Test");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        btnMessageToAdmin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMessageToAdmin.setText("Message To Admin");
        btnMessageToAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessageToAdminActionPerformed(evt);
            }
        });

        txtMessage.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Compound List:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Work Queue: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(79, 79, 79)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnRequest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCreateCompound, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addComponent(btnMessageToAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnCreateCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMessage)
                    .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMessageToAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        int selectedRow = tblCompoundHistory.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a compound to test", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtMessage.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a message ", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Compound compound = (Compound) tblCompoundHistory.getValueAt(selectedRow, 0);

        CompoundWorkRequest request = new CompoundWorkRequest();
        request.setCompound(compound);
        request.setMessage(txtMessage.getText());
        request.setSender(account);
        request.setStatus(Status.TOBETESTED);

        organization.getWorkQueue().getWorkQueue().add(request);
        account.getWorkQueue().getWorkQueue().add(request);

        JOptionPane.showMessageDialog(null, "The compound has been sent for pre-clinical tests", "Information", JOptionPane.INFORMATION_MESSAGE);

        populateWorkQueue();

        txtMessage.setText("");

    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnMessageToAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessageToAdminActionPerformed
        int selectedRow = tblWorkQueue.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request to process", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        CompoundWorkRequest request = (CompoundWorkRequest) tblWorkQueue.getValueAt(selectedRow, 4);
        if (request.getStatus() == Status.SUCCESS && request.getSender() == account) {
            ScientistApprovalJPanel approvalJPanel = new ScientistApprovalJPanel(request, account, userProcessContainer);
            userProcessContainer.add("approvalJPanel", approvalJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a successful request sent by you to approve", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnMessageToAdminActionPerformed

    private void btnCreateCompoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCompoundActionPerformed
        CreateCompoundJPanel createCompoundJPanel = new CreateCompoundJPanel(userProcessContainer, system);
        userProcessContainer.add("createCompoundJPanel", createCompoundJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateCompoundActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCompound;
    private javax.swing.JButton btnMessageToAdmin;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCompoundHistory;
    private javax.swing.JTable tblWorkQueue;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables

    public void populateCompoundHistory() {
        DefaultTableModel model = (DefaultTableModel) tblCompoundHistory.getModel();

        model.setRowCount(0);
        for (Compound compound : system.getCompoundList().getCompoundHistory()) {
            Object[] row = new Object[3];
            row[0] = compound;
            row[1] = compound.getMolecularFormula();
            row[2] = compound.getDiscoveryDate();

            model.addRow(row);
        }
    }

    public void populateWorkQueue() {
        DefaultTableModel model = (DefaultTableModel) tblWorkQueue.getModel();

        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkQueue()) {
            Object[] row = new Object[5];
            row[0] = ((CompoundWorkRequest) request).getCompound();
            row[1] = request.getSender() == null ? null : request.getSender();
            row[2] = request.getReceiver() == null ? null : request.getReceiver();
            row[3] = request.getStatus();
            row[4] = request;

            model.addRow(row);
        }
    }
}
