/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ScientistRole;

import Business.Compound.Compound;
import Business.Drug.Drug;
import Business.Ecosystem;
import Business.WorkQueue.DrugWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class MakeDrugJPanel extends javax.swing.JPanel {

    public JPanel userProcessContainer;
    public Ecosystem system;
    public DrugWorkRequest request;
    public Compound compound;

    /**
     * Creates new form MakeDrug
     */
    public MakeDrugJPanel(JPanel userProcessContainer, Ecosystem system, WorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;  
        this.compound = ((DrugWorkRequest)request).getCompound();
        this.request = (DrugWorkRequest)request;
        txtMolecularFormula.setText("");
        populateInActiveCompounds();
        populateAddedCompounds();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblCompoundList = new javax.swing.JTable();
        btnCreateDrug = new javax.swing.JButton();
        txtMolecularFormula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAddedCompoundList = new javax.swing.JTable();
        btnAddCompound = new javax.swing.JButton();
        btnRemoveCompound = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));

        tblCompoundList.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblCompoundList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compound", "Molecular Formula", "Description"
            }
        ));
        jScrollPane2.setViewportView(tblCompoundList);

        btnCreateDrug.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCreateDrug.setText("Create Drug");
        btnCreateDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDrugActionPerformed(evt);
            }
        });

        txtMolecularFormula.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Drug Formula : ");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("Back ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel6.setText("Drug Formulation");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Available Compounds");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Added Compounds");

        tblAddedCompoundList.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblAddedCompoundList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compound", "Molecular Formula"
            }
        ));
        jScrollPane3.setViewportView(tblAddedCompoundList);

        btnAddCompound.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAddCompound.setText("Add compound to Drug");
        btnAddCompound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCompoundActionPerformed(evt);
            }
        });

        btnRemoveCompound.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRemoveCompound.setText("Remove compound from drug");
        btnRemoveCompound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCompoundActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(111, 111, 111)
                                .addComponent(txtMolecularFormula)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddCompound, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addComponent(btnRemoveCompound, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(209, 209, 209)
                                        .addComponent(jLabel3)
                                        .addGap(128, 128, 128)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCreateDrug))
                                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(603, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddCompound)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRemoveCompound)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMolecularFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateDrug))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCompoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCompoundActionPerformed
        int selectedRow = tblCompoundList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a compound to add to drug", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Compound compound = (Compound) tblCompoundList.getValueAt(selectedRow, 0);
        DefaultTableModel model = (DefaultTableModel) tblAddedCompoundList.getModel();

        Object[] row = new Object[3];
        row[0] = compound;
        row[1] = compound.getMolecularFormula();
        model.addRow(row);

        txtMolecularFormula.setText(txtMolecularFormula.getText() + compound.getMolecularFormula());
    }//GEN-LAST:event_btnAddCompoundActionPerformed

    private void btnCreateDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDrugActionPerformed
        Drug drug = system.getDrugList().createDrug();
        drug.setName(txtName.getText());
        drug.setDiscoveryDate(new Date());
        drug.setMolecularFormula(txtMolecularFormula.getText());
        int rows = tblAddedCompoundList.getRowCount();
        double weight = 0;
        for (int i = 0; i < rows; i++) {
            Compound c = (Compound) tblAddedCompoundList.getValueAt(i, 0);
            if (c.isLeadComponent()) {
                drug.setDescription(c.getDescription());
            }
            weight += c.getMolecularWeight();
            drug.getCompoundList().add(c);
        }
        drug.setMolecularWeight(weight);

        request.setDrug(drug);

        JOptionPane.showMessageDialog(null, "Drug has been created", "Information", JOptionPane.INFORMATION_MESSAGE);

        txtMolecularFormula.setText("");
        txtName.setText("");
        DefaultTableModel model = (DefaultTableModel) tblAddedCompoundList.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnCreateDrugActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        int total = userProcessContainer.getComponentCount();
        DrugScientistWorkAreaJPanel manageProductCatalog = (DrugScientistWorkAreaJPanel) userProcessContainer.getComponent(total - 2);
        manageProductCatalog.populateDrugWorkQueue();
        manageProductCatalog.populateCompounds();

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRemoveCompoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCompoundActionPerformed
        int selectedRow = tblAddedCompoundList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a compound to remove from drug combination", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Compound compound = (Compound) tblAddedCompoundList.getValueAt(selectedRow, 0);
        DefaultTableModel model = (DefaultTableModel) tblAddedCompoundList.getModel();
        if (!compound.isLeadComponent()) {
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(null, "Lead component cannot be deleted", "Error", JOptionPane.ERROR_MESSAGE);
        }

        int rows = tblAddedCompoundList.getRowCount();
        txtMolecularFormula.setText("");
        for (int i = 0; i < rows; i++) {
            Compound c = (Compound) tblAddedCompoundList.getValueAt(i, 0);
            txtMolecularFormula.setText(txtMolecularFormula.getText() + c.getMolecularFormula());
        }
    }//GEN-LAST:event_btnRemoveCompoundActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCompound;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateDrug;
    private javax.swing.JButton btnRemoveCompound;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblAddedCompoundList;
    private javax.swing.JTable tblCompoundList;
    private javax.swing.JTextField txtMolecularFormula;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void populateInActiveCompounds() {
        DefaultTableModel model = (DefaultTableModel) tblCompoundList.getModel();

        model.setRowCount(0);
        for (Compound compound : system.getCompoundList().getCompoundHistory()) {
            if (!compound.isLeadComponent()) {
                Object[] row = new Object[3];
                row[0] = compound;
                row[1] = compound.getMolecularFormula();
                row[2] = compound.getDescription();

                model.addRow(row);
            }
        }
    }

    private void populateAddedCompounds() {
        DefaultTableModel model = (DefaultTableModel) tblAddedCompoundList.getModel();
        model.setRowCount(0);
        Object[] row = new Object[3];
        row[0] = compound;
        row[1] = compound.getMolecularFormula();

        model.addRow(row);
        txtMolecularFormula.setText(compound.getMolecularFormula());
    }
}
