/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Analysis;

import Business.Compound.Compound;
import Business.Disease.Disease;
import Business.Ecosystem;
import Business.Gene.Gene;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author joseph antony
 */
public class LeadCompoundAnalysisJPanel extends javax.swing.JPanel {

    public JPanel userProcessContainer;
    public Ecosystem system;
    public Network network;
    /**
     * Creates new form LeadCompoundAnalysis
     */
    public LeadCompoundAnalysisJPanel(JPanel userProcessContainer, Ecosystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.network = network;
        //network.setCompoundList(system.getCompoundList());
        //network.setDiseaseList(system.getDiseaseList());
        populateCombo();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboCompound = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAnalysis = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 204, 153));

        comboCompound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCompoundActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtAnalysis.setColumns(20);
        txtAnalysis.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txtAnalysis.setRows(5);
        jScrollPane1.setViewportView(txtAnalysis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(comboCompound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboCompoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCompoundActionPerformed
        String diseases = "";
        for(Gene gene:((Compound)comboCompound.getSelectedItem()).getDisease().getAffectedGenes()){
            if(network==null)
            for(Disease disease: system.getDiseaseList().getDiseaseCatalog()){
                for(Gene genes: disease.getAffectedGenes()){
                    if(gene == genes && disease!= ((Compound)comboCompound.getSelectedItem()).getDisease()){
                        diseases = diseases + disease.getName()+",";
                    }
                }
            }
            else
            for(Disease disease: network.getDiseaseList().getDiseaseCatalog()){
                for(Gene genes: disease.getAffectedGenes()){
                    if(gene == genes){
                        diseases = disease.getName()+",";
                    }
                }
            }
        }
        diseases = diseases.substring(0, diseases.length() - 1);
        txtAnalysis.setText("The selected compound is effective in curing "+ ((Compound)comboCompound.getSelectedItem()).getDisease().getName()+" . On further analysis, this lead compound might be effective in treating disease(s) such as "+diseases+" since they affect common genes.");
    }//GEN-LAST:event_comboCompoundActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboCompound;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAnalysis;
    // End of variables declaration//GEN-END:variables

    private void populateCombo() {
        if(network == null)
            for(Compound compound: system.getCompoundList().getCompoundHistory()){
                if(compound.isLeadComponent())
                    comboCompound.addItem(compound);
            }
        else{
            for(Compound compound: network.getCompoundList().getCompoundHistory()){
                if(compound.isLeadComponent())
                    comboCompound.addItem(compound);
            }
        }
    }
}
