/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Organization;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Medicine.Medicine;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PurchaseOrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.Organization.*;
import UserInterface.ScientistRole.*;
import java.awt.CardLayout;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;

/**
 *
 * @author joseph antony
 */
public class MedicineRequestAdminWorkQueueJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ScientistWorkArea
     */
    JPanel userProcessContainer;
    Organization organization;
    Enterprise enterprise;
    UserAccount userAccount;
    Ecosystem business;

    public MedicineRequestAdminWorkQueueJPanel(JPanel userProcessContainer, Organization organization, Enterprise enterprise, UserAccount userAccount, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        populateMedicineList();
    }

    public void populateMedicineList() {
        DefaultTableModel model = (DefaultTableModel) tblMedicineList.getModel();
        model.setRowCount(0);
        for (Medicine medicine : business.getMedicineCatalog().getMedicineList()) {
            Object[] row = new Object[3];
            row[0] = medicine;
            row[1] = medicine.getForm();
            row[2] = medicine.getUnitPrice();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblMedicineList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnRequestTablets = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRequestingMedicine = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAddtoRequestTablets = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        txtCountField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnCheckStatus = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));

        tblMedicineList.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblMedicineList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Medicine Type", "Unit Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMedicineList);
        if (tblMedicineList.getColumnModel().getColumnCount() > 0) {
            tblMedicineList.getColumnModel().getColumn(0).setResizable(false);
            tblMedicineList.getColumnModel().getColumn(1).setResizable(false);
            tblMedicineList.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel1.setText("Medicine Request Admin Work Queue");

        btnRequestTablets.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRequestTablets.setText("Request Tablets");
        btnRequestTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestTabletsActionPerformed(evt);
            }
        });

        tblRequestingMedicine.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblRequestingMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Medicine Type", "Unit Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblRequestingMedicine);
        if (tblRequestingMedicine.getColumnModel().getColumnCount() > 0) {
            tblRequestingMedicine.getColumnModel().getColumn(0).setResizable(false);
            tblRequestingMedicine.getColumnModel().getColumn(1).setResizable(false);
            tblRequestingMedicine.getColumnModel().getColumn(2).setResizable(false);
            tblRequestingMedicine.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Request message");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Medicine Details :");

        btnAddtoRequestTablets.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAddtoRequestTablets.setText("Add to Request Tablets");
        btnAddtoRequestTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoRequestTabletsActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        txtCountField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Quantity");

        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });

        btnCheckStatus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCheckStatus.setText("Check Order Status");
        btnCheckStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckStatusActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Request Details:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAddtoRequestTablets)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnRequestTablets, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCheckStatus, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(35, 35, 35)
                            .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(541, 541, 541))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtoRequestTablets)
                    .addComponent(txtCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRequestTablets, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCheckStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMessageActionPerformed

    private void btnCheckStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckStatusActionPerformed
        // TODO add your handling code here:
        MedicineRequestCheckStatusJPanel medicineRequestCheckStatus = new MedicineRequestCheckStatusJPanel(userProcessContainer, organization, enterprise, userAccount, business);
        userProcessContainer.add("MedicineRequestCheckStatus", medicineRequestCheckStatus);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCheckStatusActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddtoRequestTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoRequestTabletsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMedicineList.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a medicine for purchase request", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(txtCountField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the quantity", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
            Medicine medicine = (Medicine)tblMedicineList.getValueAt(selectedRow, 0);
            int count = parseInt(txtCountField.getText());
            DefaultTableModel model = (DefaultTableModel) tblRequestingMedicine.getModel();
            Object[] row = new Object[4];
            row[0] = medicine;
            row[1] = medicine.getForm();
            row[2] = medicine.getUnitPrice();
            row[3] = txtCountField.getText();
            model.addRow(row);
            txtCountField.setText("");

    }//GEN-LAST:event_btnAddtoRequestTabletsActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequestingMedicine.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select the medicine to be removed", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Medicine medicine = (Medicine)tblRequestingMedicine.getValueAt(selectedRow, 0);
        tblRequestingMedicine.remove(selectedRow);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnRequestTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestTabletsActionPerformed
        // TODO add your handling code here:
        int rowCount = tblRequestingMedicine.getRowCount();
        for(int i=0; i<rowCount; i++){
            PurchaseOrderWorkRequest workRequest = new PurchaseOrderWorkRequest();
            Medicine medicine = (Medicine)tblRequestingMedicine.getValueAt(i, 0);
            workRequest.setMedicine(medicine);
            workRequest.setMedicineCount(parseInt((String) tblRequestingMedicine.getValueAt(i, 3)));
            workRequest.setSender(userAccount);
            workRequest.setReceiver(null);
            workRequest.setMessage(txtMessage.getText());
            workRequest.setStatus(WorkRequest.Status.PURCHASEREQUEST);
            organization.getWorkQueue().getWorkQueue().add(workRequest);
            enterprise.getWorkQueue().getWorkQueue().add(workRequest);
        }
        JOptionPane.showMessageDialog(null, "Order Placed, You can check order status by clicking 'check order status' ");
        DefaultTableModel model = (DefaultTableModel) tblMedicineList.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnRequestTabletsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtoRequestTablets;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckStatus;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRequestTablets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblMedicineList;
    private javax.swing.JTable tblRequestingMedicine;
    private javax.swing.JTextField txtCountField;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
